name: data_fusion
channels:
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - dask
  - jupyter
  - scikit-learn
  - matplotlib
  - seaborn
  - pyarrow
  - openpyxl
  - pip
  - pip:
    - fuzzywuzzy
    - python-Levenshtein